### ISSUE TITLE
pregmatch error in SiteMeta, if excludePages include subpages

### ISSUE THREAD

**Issue by dennisbaum** [johannschopplich/kirby-helpers#2]
Hi Johann,
I get the following error, if i include subpages in the exclude.pages-Option:

```php
// Sitemap
    'kirby-extended.sitemap' => [
        'enable' => true,
        'exclude' => [
            'pages' => ['pagexy', 'pagexy/subpagexy'],
            /*
            'pages' => function () {
                return site()->index()->unlisted()->pluck('id', ',');
            },*/
            'templates' => [
                'default',
                'error',
```

![grafik](https://user-images.githubusercontent.com/562826/166912776-39aabea4-97b7-431a-838b-b6dd4228fbe1.png)
![grafik](https://user-images.githubusercontent.com/562826/166912822-068f9b93-6d25-4ce0-8e38-5ac351a95bd4.png)

In the original [SiteMeta-Plugin](https://github.com/getkirby/getkirby.com/blob/main/site/plugins/meta/src/SiteMeta.php) from Bastian,the preg_match-function is slightly different. 

```php
//if (preg_match('/^(?:' . implode('|', $excludePages) . ')$/i', $item->id())) {
if (preg_match('!^(?:' . implode('|', $pages) . ')$!i', $item->id())) {
```

if i change that line, it works for me.
Didn't you have an issue with that before?
I dont know if your SiteMeta is from an older version or if you changed that intentionally...

Would be nice, if you can have a look and maybe change the above line.
i you like me to, i can do a PR.

Thx!

**Comment by johannschopplich** [comment]
Thanks for the descriptive issue! You're right, the delimiter is wrong and thus won't catch slashes, if itself is a slash… This gotta be any other PCRE compatible delimiter.

Glad you dig into the source I forked from. Made it easier to fix. 🙂
