### ISSUE TITLE
Calrify options name

### ISSUE THREAD

**Issue by Small-Systems** [johannschopplich/kirby-helpers#7]
Hi Johann,

With the latest update you mention "Rename your config options from `kirby-helpers.<some-key>` to `johannschopplich.helpers.<some-key>`".

However, in the main Kirby config file, the name `kirby-helpers` still needs to be used (see https://github.com/johannschopplich/kirby-vue3-starterkit/blob/main/site/config/config.php).

It's very much a small detail but caused me some confusion,
Thanks,
Luke

**Comment by johannschopplich** [comment]
Great catch! Thank you! This was a leftover from converting the plugin namespace to the correct Kirby Plugin naming syntax.
